Repository mpostol/OPC-UA-OOI, pull requests merged in 2018-07, with the labels that each got.

#300 Create VS project for simulator #299
  Configuration/Core/Configuration.Core.csproj
  Configuration/Core/OPCUAOOIKey.snk
  Networking/Simulator.Boiler/AddressSpace/BaseDataVariableState.cs
  Networking/Simulator.Boiler/AddressSpace/BaseInstanceState.cs
  Networking/Simulator.Boiler/AddressSpace/BaseObjectState.cs
  Networking/Simulator.Boiler/AddressSpace/BaseVariableState.cs
  Networking/Simulator.Boiler/AddressSpace/ClassDiagram.cd
  Networking/Simulator.Boiler/AddressSpace/FiniteStateMachineState.cs
  Networking/Simulator.Boiler/AddressSpace/FolderState.cs
  Networking/Simulator.Boiler/AddressSpace/ISystemContext.cs
  Networking/Simulator.Boiler/AddressSpace/NodeState.cs
  Networking/Simulator.Boiler/AddressSpace/Opc.Ua.Classes.cs
  Networking/Simulator.Boiler/AddressSpace/ProgramStateMachineState.cs
  Networking/Simulator.Boiler/AddressSpace/PropertyState.cs
  Networking/Simulator.Boiler/AddressSpace/StateMachineState.cs
  Networking/Simulator.Boiler/Model/tempuri.org.UA.Examples.BoilerType.Classes.cs
  Networking/Simulator.Boiler/Networking.Simulator.Boiler.csproj
  Networking/Simulator.Boiler/OPCUAOOIKey.snk
  SemanticData/UANodeSetValidation/AddressSpaceContext.cs
  SemanticData/UANodeSetValidation/DataSerialization/NodeId.cs
  SemanticData/UANodeSetValidation/XML/ClassDiagram.cd
  UAObjectOrientedInternet.sln
  UAObjectOrientedInternet.sln.GhostDoc.user.dic
Labels: Architecture change

#309 Fixed starting boiler simulation & added configuration file
  Networking/Simulator.Boiler/ConfigurationDataConsumer.BoilersSet.xml
  Networking/Simulator.Boiler/Model/BoilersSet.cs
  Networking/Simulator.Boiler/Networking.Simulator.Boiler.csproj
Labels: New contenet

#311 Update the 400 up to the last modification on the master.
  Networking/Simulator.Boiler/ConfigurationDataConsumer.BoilersSet.xml
  Networking/Simulator.Boiler/Model/BoilersSet.cs
  Networking/Simulator.Boiler/Networking.Simulator.Boiler.csproj
Labels: In progress, Refactoring
